USE [master]
GO
/****** Object:  Database [EMPRESA_TEST_DB]    Script Date: 23/5/2022 17:47:45 ******/
CREATE DATABASE [EMPRESA_TEST_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EMPRESA_TEST_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER04\MSSQL\DATA\EMPRESA_TEST_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EMPRESA_TEST_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER04\MSSQL\DATA\EMPRESA_TEST_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EMPRESA_TEST_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET  MULTI_USER 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EMPRESA_TEST_DB', N'ON'
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET QUERY_STORE = OFF
GO
USE [EMPRESA_TEST_DB]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 23/5/2022 17:47:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[ID_CLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[DNI] [varchar](50) NOT NULL,
	[ID_PRODUCTO] [int] NULL,
	[ID_SERVICIO] [int] NULL,
	[ADEUDA] [bit] NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[ID_CLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 23/5/2022 17:47:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[ID_PRODUCTO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Servicio]    Script Date: 23/5/2022 17:47:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Servicio](
	[ID_SERVICIO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PRECIO] [float] NOT NULL,
 CONSTRAINT [PK_Servicio] PRIMARY KEY CLUSTERED 
(
	[ID_SERVICIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cliente]  WITH CHECK ADD  CONSTRAINT [FK_Cliente_Cliente] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[Cliente] ([ID_CLIENTE])
GO
ALTER TABLE [dbo].[Cliente] CHECK CONSTRAINT [FK_Cliente_Cliente]
GO
ALTER TABLE [dbo].[Cliente]  WITH CHECK ADD  CONSTRAINT [FK_Cliente_Producto] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[Producto] ([ID_PRODUCTO])
GO
ALTER TABLE [dbo].[Cliente] CHECK CONSTRAINT [FK_Cliente_Producto]
GO
ALTER TABLE [dbo].[Cliente]  WITH CHECK ADD  CONSTRAINT [FK_Cliente_Servicio] FOREIGN KEY([ID_SERVICIO])
REFERENCES [dbo].[Servicio] ([ID_SERVICIO])
GO
ALTER TABLE [dbo].[Cliente] CHECK CONSTRAINT [FK_Cliente_Servicio]
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_Producto] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[Producto] ([ID_PRODUCTO])
GO
ALTER TABLE [dbo].[Producto] CHECK CONSTRAINT [FK_Producto_Producto]
GO
USE [master]
GO
ALTER DATABASE [EMPRESA_TEST_DB] SET  READ_WRITE 
GO
